core/urls.py
from django.contrib import admin
from django.urls import path
from core.views import error404, sign_in, sign_up
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('error404/', error404, name='error404'),
    path('', sign_in, name='sign_in'),
    path('signIn/', sign_in, name='sign_in'),
    path('signUp/', sign_up, name = 'sign_up'),
    path('account/', include('users.urls')),
    path('manager/', include('manager.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path
from manager import views

app_name = 'manager'

urlpatterns = [
    path('dashboard', views.dashboard, name = "dashboard"),
    path('class', views.classview, name = "class"),
    path('supervise', views.supervise, name = "supervise"),
    path('classes', views.ClusterList.as_view(), name = "classes-list"),
    path('class/<int:pk>', views.ClusterDetail.as_view(), name = "classes-detail"),
    path('capture/images', views.CaptureImageList.as_view(), name = "capture-image-list"),
    path('capture/images/<int:pk>', views.CaptureImageDetail.as_view(), name = "capture-image-detail"),
    path('configures', views.ConfigureList.as_view(), name = "configure-list"),
    path('configure/<int:pk>', views.ConfigureDetail.as_view(), name = "configure-detail"),
    path('lessons', views.LessonList.as_view(), name = "lesson-list"),
    path('lesson/<int:pk>', views.LessonDetail.as_view(), name = "lesson-detail"),
    path('emotions', views.EmotionLessonList.as_view(), name = "emotion-list"),
    path('emotion/<int:lesson>', views.EmotionLessonDetail.as_view(), name = "emotion-detail"),
    path('lesson_all/<int:cluster>', views.LessonData.as_view(), name = "lesson-depend-cluster"),
    path('monitor/<int:lesson>', views.lesson_show, name = "lesson-detail"),
    path('control', views.ControlDevice.as_view(), name = "control-device"),

]

users/urls.py
from django.conf.urls import url
from django.urls import include
from users import views
from django.urls import path
app_name = 'account'

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^profile/$', views.profile, name = 'profile'),
]

templates/includes/footer.html
{% load static %}

<footer class="footer pt-3  ">
    <div class="container-fluid">
      <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-6 mb-lg-0 mb-4">
          <div class="copyright text-center text-sm text-muted text-lg-start">
            © <script>
              document.write(new Date().getFullYear())
            </script>,
            made with <i class="fa fa-heart"></i> by
            <a href="https://portal.ptit.edu.vn/" class="font-weight-bold" target="_blank">Posts and Telecommunications Institute of Technology</a>
          </div>
        </div>
        <div class="col-lg-6">
          <ul class="nav nav-footer justify-content-center justify-content-lg-end">
            <li class="nav-item">
              <a href="https://portal.ptit.edu.vn/" class="nav-link text-muted" target="_blank">PTIT HN</a>
            </li>
            <li class="nav-item">
              <a href="https://portal.ptit.edu.vn/" class="nav-link text-muted" target="_blank">About Us</a>
            </li>
            <li class="nav-item">
              <a href="https://portal.ptit.edu.vn/" class="nav-link text-muted" target="_blank">Blog</a>
            </li>
            <li class="nav-item">
              <a href="https://portal.ptit.edu.vn/" class="nav-link pe-0 text-muted" target="_blank">License</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
</footer>

templates/includes/menu.html
{% load static %}
<div class="min-height-300 bg-primary position-absolute w-100"></div>
<aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
<div class="sidenav-header">
    <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
    <a class="navbar-brand m-0" href="" target="_blank">
    <img src="{% static '/resources/assets_argon/img/logo-ct-dark.png' %}" class="navbar-brand-img h-100" alt="main_logo">
    <span class="ms-1 font-weight-bold">Admin Portal</span>
    </a>
</div>
<hr class="horizontal dark mt-0">
<div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main" >
    <ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link " href="{% url 'manager:dashboard' %}" id = 'dashboard'>
        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
            <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
        </div>
        <span class="nav-link-text ms-1 text-sm" >Dashboard</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="{% url 'manager:class' %}" id = 'class'>
        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
            <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
        </div>
        <span class="nav-link-text ms-1 text-sm">Manager Class</span>
        </a>
    </li>
    <li class="nav-item" >
        <a class="nav-link " href="{% url 'manager:supervise' %}" id =  'supervise'>
        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
            <i class="ni ni-app text-info text-sm opacity-10"></i>
        </div>
        <span class="nav-link-text ms-1 text-sm">Supervise Class</span>
        </a>
    </li>
    <li class="nav-item mt-3">
        <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Manage</h6>
    </li>
    <li class="nav-item"  >
        <a class="nav-link " href="{% url 'account:profile' %}" id = 'profile'>
        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
            <i class="ni ni-single-02 text-dark text-sm opacity-10"></i>
        </div>
        <span class="nav-link-text ms-1 text-sm">Profile</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href=""  id = 'device'>
        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
            <i class="ni ni-single-copy-04 text-warning text-sm opacity-10"></i>
        </div>
        <span class="nav-link-text ms-1 text-sm" >Device</span>
        </a>
    </li>
    </ul>
</div>
</aside>

templates/includes/nav.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
    <div class="container-fluid py-1 px-3">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-white" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-white active" aria-current="page">AdminPortal</li>
        </ol>
        <h6 class="font-weight-bolder text-white mb-0">Dashboard</h6>
      </nav>
      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
        <div class="ms-md-auto pe-md-3 d-flex align-items-center">
          <div class="input-group">
            <span class="input-group-text text-body"><i class="fas fa-search" aria-hidden="true"></i></span>
            <input type="text" class="form-control" placeholder="Type here...">
          </div>
        </div>
        <ul class="navbar-nav  justify-content-end">
          <li class="nav-item d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-white font-weight-bold px-0">
              <img src="{% static user.avatar %}" alt="" srcset="" width="50">
              <span class="d-sm-inline d-none">{{ user.fullname }}</span>
            </a>
          </li>
          <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-white p-0" id="iconNavbarSidenav">
              <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line bg-white"></i>
                <i class="sidenav-toggler-line bg-white"></i>
                <i class="sidenav-toggler-line bg-white"></i>
              </div>
            </a>
          </li>
          <li class="nav-item px-3 d-flex align-items-center">
          </li>
          <li class="nav-item dropdown pe-2 d-flex align-items-center">
            <a href="" class="nav-link text-white p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
              <li class="mb-1">
                <a class="dropdown-item border-radius-md" href="{% url 'account:login' %}">
                  <div class="d-flex py-1">
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="text-sm font-weight-normal mb-1 row">
                        <span class = 'col-2'> <i class="fa-solid fa-arrow-right-from-bracket col-2"></i></span> 
                        <span class="font-weight-bold col-6">Log out</span>
                      </h6>
                    </div>
                  </div>
                </a>
              </li>
              <li class="mb-1">
                <a class="dropdown-item border-radius-md" href="javascript:;">
                  <div class="d-flex py-1">
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="text-sm font-weight-normal mb-1 row">
                        <span class = 'col-2'><i class="fa-solid fa-circle-info"></i></span> 
                        <span class="font-weight-bold col-6">Support</span> 
                    </div>
                  </div>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
</nav>